

name: "macOS CI workflow"


on:
  push:
    branches: [ test ]



jobs:

  macos-latest:
      name: "macos-latest macos-latest 10.15.7"
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "brew cask list"
        run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
      - name: "brew list"
        run: brew list --formula #List all the installed formulas
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a                           


  macos-1015:
      name: "macos-10.15"
      runs-on: macos-10.15 # ProductVersion 10.15.7
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "brew cask list"
        run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
      - name: "brew list"
        run: brew list --formula #List all the installed formulas
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a                           

  macos-110:
      name: "macos-11.0"
      runs-on: macos-11.0 # ProductVersion 11.0.1 macOS Big Sur
      steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: "brew update"
        run: brew update      
      # - name: "brew upgrade"
      #   run: brew upgrade
      - name: "check on brew version"
        run: brew --version   #Homebrew 2.5.12   
      - name: "brew cask list"
        run:   brew list --cask #Warning: Calling brew cask list is deprecated! Use brew list [--cask] instead.
      - name: "brew list"
        # run: brew list #List all the installed formulas
        run: brew list --formula #List all the installed formulas
        # Calling `brew list` to only list formulae is disabled! Use `brew list --formula` instead
      - name: "Get OS X System Version"
        run: sw_vers       
      - name: "Get Mac System Details with system_profiler"
        run: system_profiler | more  
      - name: "osfingerprinting"
        run: uname -a                           
      # - name: "brew doctor"
      #   run: |
      #     brew doctor #Check brew for potential problems 